var cubesThree = [
    {
        Name: "Dayan Guhong V3 Magnetic ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "54mm",
        Weight: "77.3g",
        Img: "cubeslist/dayanguhv3.jpeg",
        Price: "$11.95",
        Rating: "6/10",
        Link: "https://speedcubing.org/collections/3x3x3/products/dayan-guhong-v3m",
    },
    {
        Name: "Dayan Guhong V4 Magnetic ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "66.5g",
        Img: "cubeslist/dayanguhv4.jpeg",
        Price: "$14.95",
        Rating: "9/10",
        Link: "https://speedcubing.org/collections/3x3x3/products/dayan-guhong-v4m",
    },
    {
        Name: "Dayan Tengyun M ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "55mm",
        Weight: "77.3g",
        Img: "cubeslist/dayantengm.jpeg",
        Price: "$25.95",
        Rating: "8/10",
        Link: "https://speedcubing.org/collections/dayan/products/dayan-tengyun-3x3x3-m",
    },
    {
        Name: "Dayan Tengyun Magnetic V2 ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "83g",
        Img: "cubeslist/dayantengmv2.jpeg",
        Price: "$31.95",
        Rating: "8/10",
        Link: "https://speedcubing.org/collections/dayan/products/dayan-tengyun-v2m",
    },
    {
        Name: "Gan 11 M Pro ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "63g",
        Img: "cubeslist/gan11.jpeg",
        Price: "$64.95",
        Rating: "9/10",
        Link: "https://speedcubing.org/collections/gan/products/gan-11m-pro-stickerless-black",
    },
    {
        Name: "Gan 354 Magnetic V2 ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "54mm",
        Weight: "77g",
        Img: "cubeslist/gan354v2.jpeg",
        Price: "$34.95",
        Rating: "7/10",
        Link: "https://speedcubing.org/collections/gan/products/gan-354-v2m",
    },
    {
        Name: "Gan 356 Air M ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "68g",
        Img: "cubeslist/ganairm.jpeg",
        Price: "$33.95",
        Rating: "8/10",
        Link: "https://speedcubing.org/collections/gan/products/gan-356-air-m",
    },
    {
        Name: "Gan 356 Magnetic ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "74g",
        Img: "cubeslist/ganm.jpeg",
        Price: "$32.95",
        Rating: "8/10",
        Link: "https://speedcubing.org/collections/gan/products/gan-356m",
    },
    {
        Name: "Gan 356 Magnetic LITE ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "74g",
        Img: "cubeslist/ganmlite.jpeg",
        Price: "$27.95",
        Rating: "8/10",
        Link: "none",
    },
    {
        Name: "Gan 356 RS ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "72g",
        Img: "cubeslist/ganrs.jpeg",
        Price: "$16.95",
        Rating: "5/10",
        Link: "none",
    },
    {
        Name: "Gan 356 X Magnetic V2 ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "80g",
        Img: "cubeslist/ganxv2.jpeg",
        Price: "$39.95",
        Rating: "8/10",
        Link: "none",
    },
    {
        Name: "Gan 356 XS ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "68g",
        Img: "cubeslist/ganxs.jpeg",
        Price: "$49.95",
        Rating: "9/10",
        Link: "https://speedcubing.org/collections/gan/products/gan-356-xs",
    },
    {
        Name: "Gan Speed Cube (GSC) ",
        Magnets: "No",
        Stickerless: "Yes",
        Size: "57mm",
        Weight: "83g",
        Img: "cubeslist/gansc.jpeg",
        Price: "$20.95",
        Rating: "7/10",
        Link: "none",
    },
    {
        Name: "Guoguan Yuexiao EDM ",
        Magnets: "Yes",
        Stickerless: "No",
        Size: "55.5mm",
        Weight: "72g",
        Img: "cubeslist/ganedm.jpeg",
        Price: "$24.95",
        Rating: "6/10",
        Link: "link",
    },
    {
        Name: "Mofang Jiaoshi Meilong Magnetic ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "71.8g",
        Img: "cubeslist/meilongmag.jpeg",
        Price: "$6.95",
        Rating: "7/10",
        Link: "https://speedcubing.org/collections/moyu/products/moyu-meilong-3x3x3-m",
    },
    {
        Name: "Monster Go Magnetic ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "85g",
        Img: "cubeslist/monsterm.jpeg",
        Price: "$19.95",
        Rating: "7/10",
        Link: "https://speedcubing.org/collections/gan/products/monstergo-3x3x3-m",
    },
    {
        Name: "Monster Go Traditional ",
        Magnets: "No",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "81g",
        Img: "cubeslist/monstergot.jpeg",
        Price: "$11.95",
        Rating: "6/10",
        Link: "none",
    },
    {
        Name: "Moyu RS3M 2020 ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "86g",
        Img: "cubeslist/moyurs3m.jpeg",
        Price: "$8.95",
        Rating: "6/10",
        Link: "https://speedcubing.org/collections/moyu/products/moyu-rs3m-2020",
    },
    {
        Name: "Moyu Weilong GTS2 ",
        Magnets: "No",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "80.2g",
        Img: "cubeslist/gts2.jpeg",
        Price: "$19.95",
        Rating: "7/10",
        Link: "none",
    },
    {
        Name: "Moyu Weilong GTS2 M ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "92g",
        Img: "cubeslist/gts2m.jpeg",
        Price: "$25.95",
        Rating: "8/10",
        Link: "none",
    },
    {
        Name: "Moyu Weilong GTS3 ",
        Magnets: "No",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "84g",
        Img: "cubeslist/gts3.jpeg",
        Price: "$29.95",
        Rating: "5/10",
        Link: "none",
    },
    {
        Name: "Moyu Weilong GTS3M ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "92g",
        Img: "cubeslist/gts3m.jpeg",
        Price: "$34.95",
        Rating: "8/10",
        Link: "https://speedcubing.org/collections/moyu/products/moyu-weilong-gts3m",
    },
    {
        Name: "Moyu Weilong WR ",
        Magnets: "No",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "80g",
        Img: "cubeslist/wr.jpeg",
        Price: "$29.95",
        Rating: "5/10",
        Link: "none",
    },
    {
        Name: "Moyu Weilong WR M 2020 ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "55mm",
        Weight: "Unknown",
        Img: "cubeslist/wrm2020.jpeg",
        Price: "$34.95",
        Rating: "8/10",
        Link: "https://speedcubing.org/collections/moyu/products/moyu-weilong-wrm-2020",
    },
    {
        Name: "Moyu Weilong WR M Magnetic ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "90g",
        Img: "cubeslist/wrmm.jpeg",
        Price: "$38.95",
        Rating: "7/10",
        Link: "none",
    },
    {
        Name: "MsCube MS3-V1 M ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "79g",
        Img: "cubeslist/mscubes.jpeg",
        Price: "$29.95",
        Rating: "7/10",
        Link: "none",
    },
    {
        Name: "MsCube MS3-V1 M Enhanced ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "74g",
        Img: "cubeslist/mscubee.jpeg",
        Price: "$34.95",
        Rating: "8/10",
        Link: "none",
    },
    {
        Name: "Qiyi MS Magnetic ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "57mm",
        Weight: "81.8g",
        Img: "cubeslist/qiyimsm.jpeg",
        Price: "$7.95",
        Rating: "7/10",
        Link: "link",
    },
    {
        Name: "Qiyi Thunderclap V3 M ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "89g",
        Img: "cubeslist/thunderv3.jpeg",
        Price: "$9.95",
        Rating: "7/10",
        Link: "https://speedcubing.org/collections/qiyi/products/qiyi-ms-3x3x3",
    },
    {
        Name: "Qiyi Valk 3 ",
        Magnets: "No",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "82.3g",
        Img: "cubeslist/valk3.jpeg",
        Price: "$19.95",
        Rating: "7/10",
        Link: "none",
    },
    {
        Name: "Qiyi Valk 3 Elite M ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "76g",
        Img: "cubeslist/valkelite.jpeg",
        Price: "$44.95",
        Rating: "9/10",
        Link: "https://speedcubing.org/collections/qiyi/products/qiyi-valk-3-elite-m",
    },
    {
        Name: "Qiyi Valk 3 M ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "85g",
        Img: "cubeslist/valk3.jpeg",
        Price: "$24.95",
        Rating: "8/10",
        Link: "https://speedcubing.org/collections/qiyi/products/qiyi-valk-3m",
    },
    {
        Name: "Qiyi Valk 3 Power ",
        Magnets: "No",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "87.4g",
        Img: "cubeslist/valkpower.jpeg",
        Price: "$24.95",
        Rating: "5/10",
        Link: "none",
    },
    {
        Name: "Qiyi Valk 3 Power M ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "94.4g",
        Img: "cubeslist/powerm.jpeg",
        Price: "$38.95",
        Rating: "6/10",
        Link: "none",
    },
    {
        Name: "Qiyi Wuwei M ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "55mm",
        Weight: "90g",
        Img: "cubeslist/wuweim.jpeg",
        Price: "$14.95",
        Rating: "8/10",
        Link: "https://cdn.shopify.com/s/files/1/0276/0133/8446/products/Screenshot_from_2019-12-05_18-11-59_180x.png?v=1596383584",
    },
    {
        Name: "YJ MGC Elite Magnetic ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "87g",
        Img: "cubeslist/mgcem.jpeg",
        Price: "$22.95",
        Rating: "8/10",
        Link: "none",
    },
    {
        Name: "YJ MGC Magnetic ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "85.8g",
        Img: "cubeslist/mgcm.jpeg",
        Price: "$14.95",
        Rating: "7/10",
        Link: "none",
    },
    {
        Name: "YJ Yulong V2 Magnetic ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "88.9g",
        Img: "cubeslist/yulongv2.jpeg",
        Price: "$7.95",
        Rating: "7/10",
        Link: "https://speedcubing.org/collections/yj/products/yj-yulong-v2m",
    },
    {
        Name: "YJ Zhilong Mini Magnetic ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "50mm",
        Weight: "57.5g",
        Img: "cubeslist/zhilongmini.jpeg",
        Price: "$7.95",
        Rating: "8/10",
        Link: "https://speedcubing.org/collections/yj/products/yj-zhilong-3x3x3",
    },
    {
        Name: "Yuxin Kylin V2 M ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "82.4g",
        Img: "cubeslist/kylinv2.jpeg",
        Price: "$9.95",
        Rating: "7/10",
        Link: "none",
    },
    {
        Name: "Yuxin Little Magic ",
        Magnets: "No",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "71.8g",
        Img: "cubeslist/lm.jpeg",
        Price: "$4.95",
        Rating: "6/10",
        Link: "https://speedcubing.org/collections/yuxin/products/yuxin-little-magic-3x3x3",
    },
    {
        Name: "Yuxin Little Magic M ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "78g",
        Img: "cubeslist/littlemagic.jpeg",
        Price: "$7.95",
        Rating: "8/10",
        Link: "https://speedcubing.org/collections/yuxin/products/yuxin-little-magic-3x3x3-m",
    },
    {
        Name: "Moyu RS3M 2021 Maglev ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "92g",
        Img: "cubeslist/rs3mlaglev.jpeg",
        Price: "$13.99",
        Rating: "7/10",
        Link: "https://speedcubing.org/collections/3x3x3/products/moyu-rs3m-2021-maglev",
    },
    {
        Name: "Moyu Weilong WR M 2021 Maglev ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "55mm",
        Weight: "84g",
        Img: "cubeslist/wrmmaglev.jpeg",
        Price: "$29.99",
        Rating: "8/10",
        Link: "https://speedcubing.org/collections/3x3x3/products/moyu-weilong-wrm-2021-maglev",
    },
    {
        Name: "Gan i3",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "88g",
        Img: "cubeslist/gani3.jpeg",
        Price: "$62.99",
        Rating: "9/10",
        Link: "none",
    },
    {
        Name: "Gan 12 Maglev",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "66g",
        Img: "cubeslist/ganmaglev.jpeg",
        Price: "$77.99",
        Rating: "9/10",
        Link: "none",
    },
    {
        Name: "Gan 12 M Leap",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "61g",
        Img: "cubeslist/ganmleap.jpeg",
        Price: "$66.99",
        Rating: "8/10",
        Link: "none",
    },
    {
        Name: "Gan Mini M Pro",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "53mm",
        Weight: "54g",
        Img: "cubeslist/ganminim.jpeg",
        Price: "$54.99",
        Rating: "7/10",
        Link: "https://speedcubing.org/collections/3x3x3/products/gan-mini-m-pro",
    },
    {
        Name: "Monster Go AI",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "81g",
        Img: "cubeslist/monsterai.jpeg",
        Price: "$27.99",
        Rating: "8/10",
        Link: "https://speedcubing.org/collections/3x3x3/products/monstergo-ai-3x3x3",
    },
    {
        Name: "Gan 11 M Duo",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "60g",
        Img: "cubeslist/gan11duo.jpeg",
        Price: "$46.99",
        Rating: "7/10",
        Link: "https://speedcubing.org/collections/3x3x3/products/gan-11m-duo",
    },
    {
        Name: "Gan 11 M",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "56g",
        Img: "cubeslist/gan11blank.jpeg",
        Price: "$34.99",
        Rating: "6/10",
        Link: "https://speedcubing.org/collections/3x3x3/products/gan-11-m",
    },
    {
        Name: "Gan 11 Air",
        Magnets: "No",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "50g",
        Img: "cubeslist/gan11air.jpeg",
        Price: "$23.99",
        Rating: "5/10",
        Link: "https://speedcubing.org/collections/3x3x3/products/gan-11-air",
    },
    {
        Name: "Dayan Zhanchi Pro M",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "77g",
        Img: "cubeslist/zhanchipro.jpeg",
        Price: "$34.99",
        Rating: "8/10",
        Link: "link",
    },
    {
        Name: "Gan 356 i Carry",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "77.5g",
        Img: "cubeslist/ganicarry.jpeg",
        Price: "$36.99",
        Rating: "8/10",
        Link: "https://speedcubing.org/collections/gan/products/gan-356-i-carry",
    },
    {
        Name: "X-Man Tornado V2 M",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "72g",
        Img: "cubeslist/tornadov2.jpeg",
        Price: "$24.99",
        Rating: "9/10",
        Link: "https://speedcubing.org/collections/3x3x3/products/x-man-tornado-v2m",
    },
];

window.cubesListThree = cubesThree;